const titlePort = ["","Sobre Mim","Clone de Voz","Encheu","Impressora","LokiGPT", "Visão Drumonsters", "Mina em RV", "Mais Informações"]
const titleEng =  ["","About Me","Voice Clone","Encheu","Printer","LokiGPT", "Drumonsters's Vision", "Mine in VR", "More Information"]
const paragraphPort = [
    '',
        'Como estudante de Engenharia da Computação na Universidade Federal de Itajubá,\
         estou imerso no mundo da tecnologia e inovação, conectando teoria e prática.\
          Faço parte da equipe de robótica Drumonsters, onde minha paixão por inteligência\
           artificial e visão computacional se transforma em realidade. \
           Contribuo para que nossos robôs possam interpretar seu ambiente e tomar \
           decisões inteligentes. Clique nas logos para saber mais.',

          'Embarquei em um desafio único: dar uma nova vida às vozes dos ícones culturais brasileiros Carlos Drummond e Cândido Portinari. Com a mentoria do professor Juliano de Almeida Monte-Mor, e utilizando ferramentas totalmente open-source e com poucos trechos de falas, consegui capturar a essência e personalidade de suas vozes. Um projeto que celebra a união da arte e tecnologia para preservar a história. Clique no gravador para acessar a matéria completa na VEJA.',
           'Em 2021, pela primeira vez usei inteligência artificial em um problema real da minha realidade: a previsão de enchentes em Governador Valadares. Utilizando a stack MERN, desenvolvi uma plataforma que, embora ainda esteja em fase de testes, já demonstra a capacidade de prever enchentes com 80% de precisão e até sete dias de antecedência, além de oferecer previsões personalizadas para cada residência da cidade. Clique no celular para mais informações.',
            'Em uma caminhada casual em 2018, um achado inesperado se transformou no início de uma jornada. Um computador abandonado, resgatado das ruas, foi o ponto de partida para a construção de uma impressora. O projeto viralizou no Twitter e chamou a atenção da mídia, com destaque em uma reportagem na Record. Essa pequena impressora não é apenas um exemplo de reciclagem inteligente, mas também uma demonstração do poder da engenharia aplicada. Confira a matéria clicando na impressora.',
             'Imagine um modelo que possa imitar você em conversas no WhatsApp!  O LokiGPT é minha criação mais complexa até hoje. Utilizando LLMs e ferramentas open-source, estou desenvolvendo um modelo treinado com todas as minhas conversas do WhatsApp. E futuramente, planejo criar ferramentas que permitirão que qualquer pessoa treine seu próprio modelo com suas conversas pessoais.',
              'Meu ingresso na equipe marcou o início de um desafio: aprimorar a visão computacional para localizar robôs em campo. Treinei um modelo YOLO, uma técnica avançada de detecção de objetos. O diferencial do projeto foi o uso exclusivo de dados sintéticos, o que eliminou a necessidade de coleta e classificação manual de dados. Isso não só simplificou o desenvolvimento, mas também se mostrou superior a outras técnicas de visão computacional tradicionais. Atualmente, em colaboração com o professor Juliano de Almeida Monte-Mor, estou desenvolvendo um artigo científico sobre o tema.',
               'Criei uma experiência imersiva que leva o usuário para o centro de uma mina virtual, sob a orientação do professor Juliano. Usando a tecnologia Leap Motion para o rastreamento das mãos, os visitantes podiam interagir com os minerais da região, enquanto informações detalhadas sobre cada mineral eram exibidas. Desenvolvido com Unity e C#, e experimentado através de um Oculus DK2, o projeto foi destaque em um evento no museu de Itabira, com planos de atualização para óculos de realidade virtual mais modernos. Toque no celular para saber mais.',
                'Para mais informações, clique na prancheta e acesse meu currículo em pdf. Confira meu perfil no LinkedIn clicando na logo.',
]

const paragraphEng = [
  '',
  'As a Computer Engineering student at the Federal University of Itajubá, I am immersed in the world of technology and innovation, bridging theory and practice. I am part of the Drumonsters robotics team, where my passion for artificial intelligence and computer vision becomes a reality. I contribute to our robots’ ability to interpret their environment and make intelligent decisions. Click on the logos to learn more.',
  'Embarking on a unique challenge, I sought to give new life to the voices of Brazilian cultural icons Carlos Drummond and Cândido Portinari. Using entirely open-source tools and just a few speech samples, I managed to capture the essence and personality of their voices. This project, mentored by Professor Juliano de Almeida Monte-Mor, celebrates the union of art and technology to preserve history.',
  'In 2021, for the first time, I used artificial intelligence to address a real-world problem in my community: flood prediction in Governador Valadares. Using the MERN stack, I developed a platform that, although still in the testing phase, has already shown the ability to predict floods with 80% accuracy up to seven days in advance. It also provides personalized forecasts for each residence in the city. Tap on the phone for more information.',
  "During a casual walk in 2018, an unexpected find turned into the beginning of a journey. An abandoned computer, rescued from the streets, was the starting point for building a printer. The project went viral on Twitter and caught the attention of the media, being featured in a report on Record, a Brazilian network. This small printer is not just an example of smart recycling, but also a demonstration of the power of applied engineering. Check out the story by clicking on the printer.",
  'Imagine a model that can mimic you in WhatsApp conversations! LokiGPT is my most complex creation to date. Using LLMs and open-source tools, I’m developing a model trained with all my WhatsApp conversations. And in the future, I plan to create tools that will allow anyone to train their own model with their personal conversations',
  'My joining the team marked the beginning of a challenge: to enhance computer vision for locating robots on the field. I trained a YOLO model, an advanced object detection technique. The project’s distinction was the exclusive use of synthetic data, which eliminated the need for manual data collection and classification. This not only simplified development but also proved superior to other traditional computer vision techniques. Currently, in collaboration with Professor Juliano de Almeida Monte-Mor, I am developing a scientific paper on the subject.',
  'In an innovative project, I developed an immersive experience that transports users to the center of a virtual mine. This was achieved using Unity and C#, and experienced through an Oculus DK2. The project utilizes Leap Motion technology for hand tracking, allowing visitors to interact with the region’s minerals, with detailed information about each mineral displayed. Under the guidance of Professor Juliano, the project was featured at an event at the Itabira museum, with plans for updates to more modern virtual reality glasses.',
  'For more information, click on the clipboard and access my resume in pdf. Check out my LinkedIn profile by clicking on the logo.',
]

const paragraphPos = [0,1, 1, 0, 1, 0, 1, 1, 1]

const texts = [[titlePort, paragraphPort], [titleEng, paragraphEng],paragraphPos]
export default texts
